(require-package 'helm)
(setq helm-buffers-fuzzy-matching t)
;; (global-set-key (kbd "C-x C-f") 'helm-find-files)
(global-set-key (kbd "C-c j") 'helm-mini)
;; (global-set-key (kbd "C-c k") 'helm-semantic-or-imenu)
;; (global-set-key (kbd "M-x") 'helm-M-x)
(provide 'init-helm)
